// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || 'https://vflpipmavgdoaookliwx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmbHBpcG1hdmdkb2Fvb2tsaXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NjI2NTksImV4cCI6MjA5MjMzODY1OX0.OudcUwGi1GopuQSHNPjb8VWE7PHSsl7jMf60gWQYphU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});